import React, { useEffect, useState } from 'react';
import type { Session } from '@supabase/supabase-js';
import { ArrowUpRight, ArrowRight, Activity, ShieldCheck, GitBranch, Check, LockKeyhole, FileCheck2, ScanLine, Menu, X } from 'lucide-react';
import { demoTracks } from './demo-data';
import { DemoBookingModal } from './DemoBookingModal';
import './landing.css';
import { AimiLogo } from '../AimiLogo';

export function HeroSection({ onBook }: { onBook: () => void }) {
  return <section className="aimi-hero" id="product"><div className="aimi-eyebrow"><span className="aimi-dot" /> REINVENTING ENTERPRISE TALENT EVALUATION</div>
    <h1>The behaviorals of the past are now the <span>technicals of the future.</span></h1>
    <div className="aimi-hero-bottom"><p>Interview talent like they already got the job. AIMI (AI Maturity Index) evaluates prompt discipline, behavioral judgment, and enterprise data security in real-time workplace simulations.</p><div className="aimi-actions"><button className="aimi-primary" onClick={onBook}>Request Enterprise Pilot <ArrowUpRight size={17} /></button><a href="#interactive-demo" className="aimi-secondary">Try Interactive Simulation <ArrowRight size={17} /></a></div></div>
    <div className="aimi-hero-foot"><span>HUMAN JUDGMENT. VISIBLE.</span><span>SCROLL TO STEP INSIDE <span aria-hidden="true">↓</span></span></div>
  </section>;
}

const events = ['Prompt log captured', 'Data hygiene check: PASSED — No PII leaked', 'Verification discipline: High', 'Output time: 12m 45s'];
export function TelemetryStream({ revision }: { revision: number }) {
  const [count, setCount] = useState(1);
  const [playing, setPlaying] = useState(true);
  useEffect(() => { setCount(1); }, [revision]);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setCount(n => n === 4 ? 1 : n + 1), 2600); return () => clearInterval(timer); }, [playing]);
  return <aside className="aimi-telemetry"><div className="aimi-panel-heading"><Activity size={15} /><span>BEHAVIORAL TELEMETRY</span><button onClick={() => setPlaying(!playing)} aria-label={playing ? 'Pause telemetry' : 'Play telemetry'}>{playing ? 'Pause' : 'Play'}</button></div><div className="aimi-monitor"><span className="aimi-eyebrow">ILLUSTRATIVE SESSION</span><div className="aimi-score">87<span>/100</span></div><p>Illustrative report score · human review required</p><div className="aimi-meter"><i /></div></div><div className="aimi-event-list">{events.map((event, i) => <div className={i < count ? 'is-visible' : ''} key={event}><span className="aimi-event-index">0{i + 1}</span><p>{i < count ? event : 'Awaiting simulated event…'}</p>{i < count && <Check size={13} />}</div>)}</div><p className="aimi-caption">Simulated telemetry. No personal data or real model calls in this preview.</p></aside>;
}

export function InteractiveDemoWidget() {
  const [mode, setMode] = useState<'screen' | 'superday' | 'grader'>('screen');
  const [track, setTrack] = useState(0);
  const [values, setValues] = useState<number[]>([...demoTracks[0].values]);
  const [chart, setChart] = useState('bar');
  const current = demoTracks[track];
  return <section className="aimi-section" id="interactive-demo"><div className="aimi-section-title"><div><p className="aimi-eyebrow">01 / THE WORK IS THE INTERVIEW</p><h2>See the thinking.<br /><span>Not just the answer.</span></h2></div><p>A real brief. A working canvas. An AI copilot.<br />Every decision becomes evidence.</p></div><div className="aimi-mode-tabs" aria-label="AIMI product mode"><button aria-pressed={mode === 'screen'} onClick={() => setMode('screen')}><span>AIMI SCREEN</span>40-MIN INITIAL OA / TECHNICAL ROUND</button><button aria-pressed={mode === 'superday'} onClick={() => setMode('superday')}><span>AIMI SUPERDAY</span>2 HR 15 MIN DEEP-DIVE SIMULATION</button><button aria-pressed={mode === 'grader'} onClick={() => setMode('grader')}><span>HR SCORECARD</span>GRADER WORKSPACE / HUMAN REVIEW</button></div>
    {mode === 'grader' ? <div className="aimi-grader-preview" aria-label="HR evaluation and report preview"><div className="aimi-grader-evidence"><div className="aimi-panel-heading"><span>AIMI GRADER WORKSPACE</span><span className="aimi-demo-badge">EVIDENCE / JUDGMENT / HUMAN REVIEW</span></div><p className="aimi-grader-candidate">Candidate session · {current.name} · in review</p><div className="aimi-grader-tabs"><span className="is-active">Segment deliverables</span><span>AI verification logs</span><span>Data hygiene</span><span>Shock adaptation</span><span>Quantitative checks</span><span>Raw AI history</span><span>Final recommendation</span></div><div className="aimi-grader-segments"><details open><summary>Segment 1 · Initial thesis</summary><p>Memo checkpoint and observable decision evidence.</p></details><details><summary>Segment 3 · Deal shock &amp; re-underwriting</summary><p>Revised assumptions, KPIs, owners, and thresholds.</p></details><details><summary>Segment 5 · Final deliverable</summary><p>Recommendation, risks, uncertainty, and required visual.</p></details></div></div><div className="aimi-grader-report"><span className="aimi-eyebrow">DRAFT EVALUATION</span><div className="aimi-grader-score">80.5 <small>/ 100</small></div><span className="aimi-grader-status">Human decision required</span><div className="aimi-grader-signals"><span>✓ Submitted Data Hygiene Gate</span><span>✓ Challenged AI Hallucination</span><span>✓ 5-Part Structure Followed</span></div><div className="aimi-grader-advisory"><span className="aimi-mono">SCORING ADVISORY</span><p>Rule-based deductions support calibration; the certified human grader controls the final score and decision.</p></div><div className="aimi-grader-rubric"><span className="aimi-mono">RUBRIC CRITERIA</span><p><strong>AI-Assisted Planning</strong><b>16.7%</b></p><p><strong>Data Governance</strong><b>16.7%</b></p><p><strong>Shock Adaptation</strong><b>16.7%</b></p></div></div></div> : <>
    <div id="tracks" className="aimi-track-tabs" aria-label="Simulation tracks">{demoTracks.map((item, i) => <button key={item.id} aria-pressed={track === i} onClick={() => { setTrack(i); setValues([...item.values]); }}><span>{item.short}</span>{item.name}<ArrowUpRight size={15} /></button>)}</div>
    <div className="aimi-workspace"><div className="aimi-workspace-main"><div className="aimi-panel-heading"><span className="aimi-window-dots" aria-hidden="true">● ● ●</span><span>AIMI {mode === 'screen' ? 'SCREEN / WORKSPACE' : 'SUPERDAY / WORKSPACE'}</span><span className="aimi-demo-badge">INTERACTIVE PREVIEW</span></div><div className="aimi-canvas"><div className="aimi-canvas-title"><span className="aimi-eyebrow">YOUR ASSIGNMENT</span><span className="aimi-mono">{mode === 'screen' ? '12:45 / 40:00' : '42:10 / 135:00'}</span></div><h3>{current.title}</h3><details open><summary>Scenario brief</summary><p>{current.brief}</p></details><div className="aimi-exhibit-heading"><span>EXHIBIT A / {current.exhibit}</span><label>Chart <select aria-label="Chart type" value={chart} onChange={e => setChart(e.target.value)}><option value="bar">Bar</option><option value="line">Line</option></select></label></div><div className="aimi-visual-builder"><table><thead><tr><th>Period / segment</th><th>Value</th></tr></thead><tbody>{current.labels.map((label, i) => <tr key={label}><td>{label}</td><td><input aria-label={`${label} value`} type="number" min="0" max="999" value={values[i]} onChange={e => setValues(v => v.map((n, j) => j === i ? Math.max(0, Math.min(999, Number(e.target.value))) : n))} /></td></tr>)}</tbody></table><div className="aimi-chart" role="img" aria-label={`${chart} chart: ${current.labels.map((l, i) => `${l} ${values[i]}`).join(', ')}`}>
    {chart === 'bar' ? values.map((v, i) => <div className="aimi-bar-column" key={i}><span>{v}</span><div style={{ height: `${Math.max(2, v / Math.max(1, ...values) * 110)}px` }} /><small>{current.labels[i]}</small></div>) : <svg aria-hidden="true" viewBox="0 0 270 160"><polyline fill="none" stroke="white" strokeWidth="2" points={values.map((v, i) => `${25 + i * 110},${135 - v / Math.max(1, ...values) * 110}`).join(' ')} />{values.map((v, i) => <g key={i}><circle cx={25 + i * 110} cy={135 - v / Math.max(1, ...values) * 110} r="4" fill="white" /><text x={25 + i * 110} y="156" textAnchor="middle" fill="#aaa" fontSize="10">{current.labels[i]}</text></g>)}</svg>}</div></div><div className="aimi-canvas-footer"><span><Check size={13} /> Edit a cell. Watch the evidence change.</span><button onClick={() => setValues([...current.values])}>Reset exhibit ↺</button></div></div></div><TelemetryStream revision={track} /></div>
    <div className="aimi-product-links"><a href="/screen">AIMI Screen <span>Focused role assessment</span><ArrowUpRight size={17} /></a><a href="/superday">AIMI Superday <span>Multi-phase workplace simulation</span><ArrowUpRight size={17} /></a><a href="#pricing">Full AIMI Talent OS <span>Screen + Superday hiring pipeline</span><ArrowUpRight size={17} /></a></div></>}
  </section>;
}

export function RoadmapBuilderSection() {
  const [selected, setSelected] = useState(0);
  const [steps, setSteps] = useState([{ title: 'Frame the decision', owner: 'Product lead', threshold: 10 }, { title: 'Validate the evidence', owner: 'Data analyst', threshold: 5 }, { title: 'Launch & monitor', owner: 'Operations lead', threshold: 15 }]);
  const step = steps[selected];
  const update = (field: 'owner' | 'threshold', value: string | number) => setSteps(all => all.map((s, i) => i === selected ? { ...s, [field]: value } : s));
  return <section className="aimi-section aimi-roadmap" id="roadmap"><div><p className="aimi-eyebrow">02 / STRATEGY BEFORE EXECUTION</p><h2>Everyone is<br />a PM now.</h2><p className="aimi-section-copy">AI can generate an answer. Can your candidate build a plan? Reveal how they sequence work, assign accountability, and decide when to change course.</p><div className="aimi-small-note"><GitBranch size={17} /> Dependencies. Owners. Reversal thresholds.</div></div><div className="aimi-roadmap-widget"><div className="aimi-panel-heading"><GitBranch size={15} /> EXECUTION ROADMAP <span className="aimi-demo-badge">EDITABLE PREVIEW</span></div><div className="aimi-steps">{steps.map((s, i) => <button key={s.title} aria-pressed={selected === i} onClick={() => setSelected(i)}><span>0{i + 1}</span><div><strong>{s.title}</strong><small>{i === 0 ? 'START / DAY 1' : `DEPENDS ON 0${i} / DAY ${i * 3 + 1}`}</small></div><ArrowRight size={16} /></button>)}</div><div className="aimi-step-editor"><label>Operational owner<input value={step.owner} maxLength={60} onChange={e => update('owner', e.target.value)} /></label><label>Reversal threshold <span>{step.threshold}%</span><input type="range" min="1" max="30" value={step.threshold} onChange={e => update('threshold', Number(e.target.value))} /></label><p>Pause “{step.title.toLowerCase()}” if error rate exceeds {step.threshold}%. {step.owner || 'Assign an owner'} reviews the evidence before the next stage.</p></div></div></section>;
}

export function DynamicConstraintsSection() {
  return <section className="aimi-section aimi-shocks" id="dynamic-constraints"><div className="aimi-shocks-copy"><p className="aimi-eyebrow"><span className="aimi-dot" /> DYNAMIC VS. STATIC EVALUATION</p><h2>Static OAs create robotic candidates. <span>AIMI evaluates real-time adaptability.</span></h2><p>Traditional Superdays and legacy Online Assessments (OAs) are static exams—candidates simply memorize answer keys, prompt templates, and pre-baked case solutions. AIMI replaces static tests with <strong>Mid-Scenario Constraints (Dynamic Shocks)</strong>.</p><div className="aimi-shock-callout"><span className="aimi-mono">THE MINUTE 20 EVENT</span><p>At Minute 20 of an AIMI Screen or Minute 60 of an AIMI Superday, a sudden market shift, revised data exhibit, or urgent stakeholder email hits the candidate’s workspace. Candidates must pivot, update their financial models or roadmap dependencies, and defend their revised decisions under real-time pressure.</p></div></div><div className="aimi-shock-visual" aria-label="Illustration of a dynamic shock entering a live assessment"><div className="aimi-shock-timeline"><span>MIN 00</span><i /><span>MIN 20</span><i className="aimi-shock-line" /><span>MIN 40</span></div><div className="aimi-shock-card aimi-shock-before"><span className="aimi-mono">01 / INITIAL BRIEF</span><strong>Build the rollout plan</strong><small>Scenario, exhibits, roadmap</small></div><div className="aimi-shock-card aimi-shock-event"><span className="aimi-mono">⚡ DYNAMIC SHOCK / LIVE</span><strong>Urgent stakeholder email</strong><small>North Hub inventory error rate rises 15%. Reallocate the remaining budget.</small></div><div className="aimi-shock-card aimi-shock-after"><span className="aimi-mono">02 / OBSERVED RESPONSE</span><strong>Revise and defend</strong><small>Decision change · dependencies · reversal threshold</small></div><div className="aimi-shock-quote">IF YOU ARE A COMPANY IN NEED OF CRITICAL THINKERS QUICK ON THEIR FEET, THEN AIMI IS THE PERFECT HIRING SYSTEM FOR YOU.</div></div></section>;
}

const reportDimensions = [
  ['Prompt & AI Discipline', 86, 'Structured prompts, recorded Copilot history, and evidence-backed refinement.', 'Observed'],
  ['Data Governance & Security', 94, 'Data hygiene gate passed; blocked sensitive-data attempts do not reach the provider.', 'Observed'],
  ['Critical Thinking & Adaptability', 82, 'Post-shock checkpoint shows revised assumptions, KPIs, owners, and thresholds.', 'Review'],
  ['Domain Execution', 89, 'Final recommendation, quantitative checks, risks, uncertainty, and required visual are present.', 'Observed'],
] as const;

export function EvaluationReportPreview() {
  const [selected, setSelected] = useState(0);
  const total = Math.round(reportDimensions.reduce((n, [, score]) => n + score, 0) / reportDimensions.length);
  const dimension = reportDimensions[selected];
  return <section className="aimi-section aimi-report" id="report-preview"><div className="aimi-section-title"><div><p className="aimi-eyebrow">04 / ENTERPRISE EVALUATION &amp; RUBRIC REPORT</p><h2>Evidence your<br /><span>HR team can act on.</span></h2></div><p>Human judgment stays in control.<br />AIMI makes the evidence legible.</p></div><div className="aimi-report-grid"><div className="aimi-report-card"><div className="aimi-report-card-top"><span className="aimi-eyebrow">ILLUSTRATIVE CANDIDATE REPORT</span><span className="aimi-mono">SCREEN + SUPERDAY</span></div><div className="aimi-report-score"><strong>{total}</strong><span>/ 100<br /><small>AI MATURITY INDEX</small></span></div><p className="aimi-report-summary">Strong evidence of structured AI use and safe data handling. Review the adaptation record before a final hiring decision.</p><div className="aimi-report-flags"><span className="is-positive">✓ Hygiene gate passed</span><span className="is-positive">✓ Prompt audit complete</span><span className="is-review">! Shock response review</span></div></div><div className="aimi-rubric-list"><p className="aimi-eyebrow">RUBRIC DIMENSIONS / 1–100</p>{reportDimensions.map(([name, score, copy, status], i) => <button key={name} aria-pressed={selected === i} onClick={() => setSelected(i)}><span className="aimi-rubric-score">{score}</span><span><strong>{name}</strong><small>{copy}</small></span><em>{status}</em></button>)}<div className="aimi-report-takeaway"><span className="aimi-mono">EMPLOYER TAKEAWAY</span><p>{dimension[2]}</p></div></div></div></section>;
}

export function LandingPage({ session, onSignOut }: { session: Session | null; onSignOut: () => void }) {
  const [booking, setBooking] = useState(false);
  const [menu, setMenu] = useState(false);
  const nav = [['Product', '#product'], ['Interactive Demo', '#interactive-demo'], ['Tracks', '#tracks'], ['Security', '#security'], ['Enterprise Pricing', '#pricing']];
  return <div className="aimi-landing bg-zinc-950 text-zinc-50"><a className="aimi-skip" href="#main">Skip to content</a><header className="aimi-header"><a href="/" className="aimi-brand"><AimiLogo /></a><nav aria-label="Main navigation" className={menu ? 'is-open' : ''}>{nav.map(([label, href]) => <a key={label} href={href} onClick={() => setMenu(false)}>{label}</a>)}</nav><div className="aimi-header-actions">{session ? <button className="aimi-text-button" onClick={onSignOut}>Sign out</button> : <a href="/screen">Candidate Login</a>}<button className="aimi-primary" onClick={() => setBooking(true)}>Book Demo <ArrowUpRight size={15} /></button><button className="aimi-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div></header><main id="main"><HeroSection onBook={() => setBooking(true)} /><div className="aimi-thesis"><span>WE ARE THE MOST TRANSPARENT WAY TO HIRE.</span><span>PROMPT DISCIPLINE <i>+</i> JUDGMENT <i>+</i> EXECUTION</span></div><InteractiveDemoWidget /><DynamicConstraintsSection /><RoadmapBuilderSection /><EvaluationReportPreview /><section id="security" className="aimi-section"><div className="aimi-section-title"><div><p className="aimi-eyebrow">03 / TRUST IS PART OF THE ASSESSMENT</p><h2>Better judgment.<br /><span>Less enterprise risk.</span></h2></div><p>Evaluate safe AI use before talent<br />touches real production data.</p></div><div className="aimi-security-grid">{[
    [LockKeyhole, 'Zero-retention safeguards', 'Enterprise provider controls and contract verification gate AI access. Retention terms are confirmed for your deployment.'],
    [ScanLine, 'PII exposure flagging', 'Data hygiene gates and sensitive-data checks reveal how candidates handle confidential information under pressure.'],
    [ShieldCheck, 'Hallucination verification', 'Evaluate whether candidates verify outputs, challenge assumptions, and trace recommendations back to source evidence.'],
    [FileCheck2, 'Compliance audit trails', 'Recorded evidence supports human review and your AEDT / EU AI Act compliance process. Legal compliance requires a separate assessment.'],
  ].map(([Icon, title, copy]) => { const Symbol = Icon as typeof ShieldCheck; return <article key={String(title)}><Symbol size={23} strokeWidth={1.3} /><h3>{String(title)}</h3><p>{String(copy)}</p></article>; })}</div></section><section id="pricing" className="aimi-section aimi-pricing"><div><p className="aimi-eyebrow">ENTERPRISE PILOTS / BUILT AROUND YOUR TEAM</p><h2>Your next great hire.<br /><span>Now, with the evidence.</span></h2><p>Choose your tracks, define your cohort, and explore a tailored pilot.<br />Enterprise pricing is scoped to assessment volume and support needs.</p></div><button className="aimi-primary" onClick={() => setBooking(true)}>Book Demo / Request Pilot <ArrowUpRight size={18} /></button></section></main><footer className="aimi-footer"><a href="/" className="aimi-brand"><AimiLogo compact /></a><div><a href="/screen">AIMI Screen ↗</a><a href="/superday">AIMI Superday ↗</a><a href="/admin">Employer / Admin ↗</a><a href="/grader">Grader Portal ↗</a></div><span>© {new Date().getFullYear()} AIMI</span></footer>{booking && <DemoBookingModal onClose={() => setBooking(false)} />}</div>;
}
