// Pure arithmetic shared by candidate calculators and reviewer baselines; no scenario answers here.
export interface DcfInputs {revenue:number;growth:number[];margins:number[];daRate:number;capexRate:number;nwcRate:number;taxRate:number;wacc:number;terminalGrowth:number;cash:number;debt:number;}
export function calculateDcf(a:DcfInputs){
 if(a.growth.length!==5||a.margins.length!==5||!Object.values(a).flat().every(Number.isFinite)||a.revenue<=0||a.wacc<=a.terminalGrowth||a.wacc<=-1||a.terminalGrowth<=-1||a.growth.some(g=>g<=-1))throw new Error('Enter five forecast years, positive starting revenue, and WACC greater than terminal growth. Use decimal rates.');
 let revenue=a.revenue;const years=a.growth.map((growth,i)=>{const previous=revenue;revenue*=1+growth;const ebitda=revenue*a.margins[i],da=revenue*a.daRate,ebit=ebitda-da,taxes=ebit*a.taxRate,nopat=ebit-taxes,capex=revenue*a.capexRate,nwc=(revenue-previous)*a.nwcRate,fcf=nopat+da-capex-nwc,pv=fcf/(1+a.wacc)**(i+1);return {year:i+1,revenue,ebitda,da,ebit,taxes,nopat,capex,nwc,fcf,pv};});
 const terminal=years[4].fcf*(1+a.terminalGrowth)/(a.wacc-a.terminalGrowth),terminalPV=terminal/(1+a.wacc)**5,ev=years.reduce((s,y)=>s+y.pv,0)+terminalPV,netDebt=a.debt-a.cash;
 return {years,terminal,terminalPV,ev,netDebt,equity:ev-netDebt};
}
export function calculateLaborValue(rows:{active:number;hours:number;cost:number}[],realization:number,programCost:number){if(!rows.length||rows.some(r=>Object.values(r).some(v=>!Number.isFinite(v)||v<0))||!Number.isFinite(realization)||realization<0||realization>1||programCost<=0)throw new Error('Enter nonnegative operating inputs, realization between 0 and 1, and positive program cost.');const functions=rows.map(r=>({potential:r.active*r.hours*52*r.cost,realized:r.active*r.hours*52*r.cost*realization}));const potential=functions.reduce((s,r)=>s+r.potential,0),realized=potential*realization;return {functions,potential,realized,programCost,netValue:realized-programCost,roi:(realized-programCost)/programCost,realization};}
