import React,{useState} from 'react';
import type {AssessmentWork,AnalysisEntry} from '../../types/work';
import {calculateDcf,calculateLaborValue} from '../../services/calculations';
export function Calculator({trackId,work,onChange}:{trackId:string;work:AssessmentWork;onChange:(w:AssessmentWork)=>void}){
 const [error,setError]=useState(''),[message,setMessage]=useState('');
 if(!['consulting','investment-banking'].includes(trackId))return null;
 const prefix=trackId==='consulting'?'labor.input.':'dcf.input.';
 const get=(key:string)=>work.analysis.find(a=>a.metric===prefix+key)?.value;
 function update(key:string,value:number){const metric=prefix+key,previous=work.analysis.find(a=>a.metric===metric);onChange({...work,analysis:[...work.analysis.filter(a=>a.metric!==metric),{id:previous?.id||crypto.randomUUID(),metric,value,formula:'Candidate-entered assumption',source:'Candidate model input; compare with exhibits'}]});setMessage('');}
 const input=(key:string,label:string)=><label className="work-field" key={key}><span>{label}</span><input type="number" step="any" aria-label={label} value={get(key)??''} onChange={e=>update(key,Number(e.target.value))}/></label>;
 function calculate(){setError('');try{const required=trackId==='investment-banking'?['revenue','daRate','capexRate','nwcRate','taxRate','wacc','terminalGrowth','cash','debt',...Array.from({length:5},(_,i)=>'growth'+i),...Array.from({length:5},(_,i)=>'margin'+i)]:['realization','programCost',...Array.from({length:4},(_,i)=>['active','hours','cost'].map(k=>k+i)).flat()];if(required.some(k=>get(k)===undefined))throw new Error('Complete every calculator input from the exhibits or state your alternative assumption.');
 const outputs:Record<string,{value:number;formula:string}>={};
 if(trackId==='investment-banking'){const result=calculateDcf({revenue:get('revenue')!,growth:Array.from({length:5},(_,i)=>get('growth'+i)!),margins:Array.from({length:5},(_,i)=>get('margin'+i)!),daRate:get('daRate')!,capexRate:get('capexRate')!,nwcRate:get('nwcRate')!,taxRate:get('taxRate')!,wacc:get('wacc')!,terminalGrowth:get('terminalGrowth')!,cash:get('cash')!,debt:get('debt')!});for(const y of result.years)for(const [key,value] of Object.entries(y))if(key!=='year')outputs[`year${y.year}.${key}`]={value,formula:'Revenue → EBITDA → D&A → EBIT → tax → NOPAT + D&A − CapEx − change in NWC → discounted UFCF'};for(const key of ['terminal','terminalPV','ev','equity','netDebt'] as const)outputs[key]={value:result[key],formula:key==='equity'?'Enterprise value − (debt − cash)':'Five-year UFCF discounted at WACC; terminal FCF × (1 + g) / (WACC − g), discounted five years'};outputs.wacc={value:get('wacc')!,formula:'Candidate input'};outputs.terminalGrowth={value:get('terminalGrowth')!,formula:'Candidate input'};}
 else{const result=calculateLaborValue(Array.from({length:4},(_,i)=>({active:get('active'+i)!,hours:get('hours'+i)!,cost:get('cost'+i)!})),get('realization')!,get('programCost')!);for(const [key,value] of Object.entries(result))if(typeof value==='number')outputs[key]={value,formula:'Potential = active users × weekly hours × 52 × hourly cost; realized = potential × realization; net = realized − program cost; ROI = net / cost'};result.functions.forEach((r,i)=>{outputs[`function${i+1}.potential`]={value:r.potential,formula:'Active users × weekly hours × 52 × hourly cost'};outputs[`function${i+1}.realized`]={value:r.realized,formula:'Potential × realization'};});}
 const generated:AnalysisEntry[]=Object.entries(outputs).map(([metric,o])=>({id:work.analysis.find(a=>a.metric===metric)?.id||crypto.randomUUID(),metric,...o,source:'Candidate calculator inputs; verify assumptions against exhibits'}));onChange({...work,analysis:[...work.analysis.filter(a=>!(a.metric in outputs)),...generated]});setMessage('Calculated outputs saved to the analysis ledger below. Recalculate after changing inputs.');
 }catch(e){setError((e as Error).message);}}
 return <section className="work-card"><h2>{trackId==='investment-banking'?'Five-year DCF workbench':'Reported vs. realized value workbench'}</h2><p className="work-muted">Populate inputs from the exhibits. Rates use decimals; IB currency uses USD millions. Outputs include formulas in your analysis ledger. Test alternatives and explain changed assumptions.</p>{trackId==='investment-banking'?<><div className="work-grid-2">{[['revenue','Starting revenue'],['cash','Cash'],['debt','Debt'],['daRate','D&A / revenue'],['capexRate','CapEx / revenue'],['nwcRate','NWC / annual revenue change'],['taxRate','Tax rate'],['wacc','WACC'],['terminalGrowth','Terminal growth']].map(([key,label])=>input(key,label))}</div><div className="work-table-wrap"><table><thead><tr><th>Year</th><th>Revenue growth</th><th>EBITDA margin</th></tr></thead><tbody>{Array.from({length:5},(_,i)=><tr key={i}><td>{i+1}</td><td>{input('growth'+i,`Year ${i+1} revenue growth`)}</td><td>{input('margin'+i,`Year ${i+1} EBITDA margin`)}</td></tr>)}</tbody></table></div></>:<><div className="work-grid-2">{input('realization','Realization factor')}{input('programCost','Annual program cost')}</div>{['Operations','Support','Sales','Finance'].map((name,i)=><div key={name} className="border-t mt-4 pt-4"><h3>{name}</h3><div className="grid sm:grid-cols-3 gap-3">{input('active'+i,`${name} active users`)}{input('hours'+i,`${name} weekly hours saved / active user`)}{input('cost'+i,`${name} hourly labor cost`)}</div></div>)}</>}{error&&<p role="alert" className="work-warning">{error}</p>}{message&&<p role="status" className="work-muted">{message}</p>}<button className="work-primary mt-4" onClick={calculate}>Calculate and update analysis ledger</button></section>;
}
