import React,{useState} from 'react';
import type {AssessmentWork} from '../../types/work';
import type {TrackConfig} from '../../types';
import {Field,Markdown} from './Primitives';
export function Logbook({work,onChange,phase,track,chats,hygiene,events,onHygiene}:{work:AssessmentWork;onChange:(w:AssessmentWork)=>void;phase:number;track:TrackConfig;chats:any;hygiene:any;events:any[];onHygiene:()=>void}) {
 const [tab,setTab]=useState('Assumptions');const change=(group:'assumptions'|'verifications',id:string,patch:any)=>onChange({...work,[group]:work[group].map(x=>x.id===id?{...x,...patch}:x)});
 return <div className="work-stack"><nav className="work-tabs">{['Assumptions','AI verification','Data hygiene','AI history'].map(t=><button key={t} onClick={()=>setTab(t)} aria-pressed={tab===t}>{t}</button>)}</nav>
 {tab==='Assumptions'&&<><p className="work-muted">Record the suspected driver, evidence and uncertainty. Explain revisions after the scenario update; earlier segment snapshots remain available to the grader.</p>{work.assumptions.map(a=><section className="work-card" key={a.id}><p className="work-eyebrow">Created in segment {a.phase}</p><Field label="Assumption" value={a.statement} onChange={statement=>change('assumptions',a.id,{statement})}/><Field label="Evidence supporting this assumption" value={a.evidence} onChange={evidence=>change('assumptions',a.id,{evidence})}/><Field label="What is uncertain?" value={a.uncertainty} onChange={uncertainty=>change('assumptions',a.id,{uncertainty})}/><label className="work-field"><span>Assumption confidence</span><select aria-label="Assumption confidence" value={a.confidence} onChange={e=>change('assumptions',a.id,{confidence:e.target.value})}><option value="">Select confidence</option>{['high','medium','low'].map(c=><option key={c}>{c}</option>)}</select></label><Field label="Revision reason after new information" value={a.revisionReason} onChange={revisionReason=>change('assumptions',a.id,{revisionReason})}/></section>)}<button className="work-primary" onClick={()=>onChange({...work,assumptions:[...work.assumptions,{id:crypto.randomUUID(),phase,statement:'',evidence:'',uncertainty:'',confidence:'',revisionReason:''}]})}>Add assumption</button></>}
 {tab==='AI verification'&&<><p className="work-muted">Review a supplied AI exhibit or a Copilot response. Cite an independent source or calculation; recording a challenge does not automatically prove it correct.</p>{work.verifications.map(v=><section className="work-card" key={v.id}><p className="work-eyebrow">Segment {v.phase} · Review {v.id.slice(0,8)}</p><label className="work-field"><span>AI source</span><select aria-label="AI source" value={v.source} onChange={e=>change('verifications',v.id,{source:e.target.value})}><option value="">Select source</option>{track.exhibits.filter(e=>e.type==='ai-sample').map(e=><option key={e.id} value={e.id}>Exhibit {e.number}: {e.title}</option>)}{Object.values(chats).flat().filter((m:any)=>m.sender==='assistant').map((m:any)=><option value={m.id} key={m.id}>Copilot · {m.content.slice(0,70)}</option>)}</select></label>{track.exhibits.find(e=>e.id===v.source)&&<details><summary>Read source</summary><Markdown text={track.exhibits.find(e=>e.id===v.source)!.content||''}/></details>}
 <Field label="Claim reviewed" value={v.claim} onChange={claim=>change('verifications',v.id,{claim})}/><div className="work-grid-2"><label className="work-field"><span>Claim classification</span><select aria-label="Claim classification" value={v.classification} onChange={e=>change('verifications',v.id,{classification:e.target.value})}><option value="">Choose classification</option>{['supported','plausible','unsupported'].map(x=><option key={x}>{x}</option>)}</select></label><label className="work-field"><span>Disposition</span><select aria-label="Disposition" value={v.decision} onChange={e=>change('verifications',v.id,{decision:e.target.value})}><option value="">Choose disposition</option>{['accept','modify','reject'].map(x=><option key={x}>{x}</option>)}</select></label></div>
 <Field label="What is unsupported, incomplete, or defensible?" value={v.issue} onChange={issue=>change('verifications',v.id,{issue})}/><Field label="Independent evidence / calculation and result" value={v.evidence} onChange={evidence=>change('verifications',v.id,{evidence})}/><Field label="Corrected wording" value={v.correction} onChange={correction=>change('verifications',v.id,{correction})}/><Field label="Validation performed or still needed" value={v.validation} onChange={validation=>change('verifications',v.id,{validation})}/></section>)}<button className="work-primary" onClick={()=>onChange({...work,verifications:[...work.verifications,{id:crypto.randomUUID(),phase,source:'',claim:'',classification:'',decision:'',issue:'',evidence:'',correction:'',validation:''}]})}>Add AI review</button></>}
 {tab==='Data hygiene'&&<><p>{hygiene?'Your single data hygiene attempt is recorded. Copilot access is unlocked.':'Complete field classifications before AI use.'}</p><button className="work-primary" onClick={onHygiene}>Review field decisions</button>{hygiene?.map((r:any)=><section className="work-card" key={r.fieldName}><strong>{r.fieldName} · {r.action}</strong><p>{r.rationale}</p></section>)}{events.map((e,i)=><div className="work-warning" key={i}>{e.type} · segment {e.phase} · {e.at}<p>{e.fields?.join(', ')||(e.type==='HYGIENE_SUBMITTED'?'Single attempt recorded.':'See recorded event.')}</p></div>)}</>}
 {tab==='AI history'&&<>{Object.entries(chats).map(([p,messages]:any)=><section className="work-card" key={p}><h3>Segment {p}</h3>{messages.length===0&&<p className="work-muted">No AI interactions.</p>}{messages.map((m:any)=><article className="work-log-message" key={m.id}><strong>{m.sender} · {m.timestamp}</strong><p className="whitespace-pre-wrap">{m.content}</p><small>{m.promptLogged?.purpose}</small></article>)}</section>)}</>}
 </div>;
}
export function HygieneEditor({track,initial,onSubmit,error,busy}:{track:TrackConfig;initial:any[];onSubmit:(rows:any[])=>void;error:string;busy:boolean}) {
 const [rows,setRows]=useState<any[]>(()=>track.dataGate!.fields.map(f=>initial?.find(r=>r.fieldName===f.fieldName)||{fieldName:f.fieldName,action:'',rationale:''}));
 return <form className="work-stack" onSubmit={e=>{e.preventDefault();if(!initial)onSubmit(rows);}}><p>{initial?'Your submitted answers are read-only.':'One attempt. Submitting unlocks Copilot regardless of accuracy. Gate accuracy multiplies your final Data Hygiene pillar score.'}</p><fieldset disabled={busy||!!initial} className="work-stack"><p>{track.dataGate?.description}</p>{track.dataGate!.fields.map((f,i)=><section className="work-card" key={f.fieldName}><h3>{f.fieldName}</h3><p className="work-muted">{f.description} · {f.sensitivityLevel}</p><label className="work-field"><span>Handling for {f.fieldName}</span><select aria-label={`Handling for ${f.fieldName}`} required value={rows[i].action} onChange={e=>setRows(r=>r.map((x,j)=>i===j?{...x,action:e.target.value}:x))}><option value="">Choose handling</option>{['use-as-is','aggregate','redact','exclude'].map(a=><option key={a} value={a}>{a}</option>)}</select></label><Field label={`Rationale for ${f.fieldName}`} value={rows[i].rationale} onChange={rationale=>setRows(r=>r.map((x,j)=>i===j?{...x,rationale}:x))}/></section>)}{error&&<p role="alert" className="work-warning">{error}</p>}<button disabled={busy||rows.some(r=>!r.action||!r.rationale.trim())} className="work-primary">{initial?'Attempt submitted':'Submit data hygiene attempt'}</button></fieldset></form>;
}
