import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import React,{useEffect,useRef} from 'react';
export function Field({label,value,onChange,rows=3,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;rows?:number;placeholder?:string}) {return <label className="work-field"><span>{label}</span><textarea aria-label={label} rows={rows} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;}
export function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}) {const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),select:not(:disabled),[tabindex="0"]')||[]);if(!els.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);prev?.focus();};},[]);return <div className="work-overlay"><div ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} className="work-modal"><header><h2>{title}</h2><button aria-label="Close dialog" onClick={onClose}>✕</button></header><div className="work-modal-body">{children}</div></div></div>;}
// Preserve code literals; normalize legacy double-escaped line endings only in prose.
export function normalizeTranscript(text:string){return text.split(/(```[\s\S]*?(?:```|$)|`[^`]*`)/g).map((part,i)=>i%2?part:part.replace(/\\r\\n|\\n/g,'\n')).join('');}
function safeBreaks(){return(tree:any)=>{const walk=(node:any)=>{if(node.type==='html'&&/^<br\s*\/?\s*>$/i.test(node.value.trim())){node.type='break';delete node.value;}node.children?.forEach(walk);};walk(tree);};}
// Stable component identities preserve the table DOM and scrollLeft during streaming renders.
const stopTableGesture=(event:React.SyntheticEvent)=>event.stopPropagation();
function MarkdownTable({children}:{children?:React.ReactNode}) {return <div className="work-table-wrap overflow-x-auto w-full block scrollbar-thin" tabIndex={0} role="region" aria-label="Scrollable table" onTouchStart={stopTableGesture} onTouchMove={stopTableGesture} onWheel={stopTableGesture}><table>{children}</table></div>;}
const markdownComponents={table:MarkdownTable,img:({alt}:{alt?:string})=><span>{alt}</span>};
export function Markdown({text}:{text:string}) {return <div className="work-prose"><ReactMarkdown remarkPlugins={[remarkGfm,safeBreaks]} skipHtml components={markdownComponents}>{normalizeTranscript(text)}</ReactMarkdown></div>;}
