import React,{useEffect,useMemo,useRef,useState} from 'react';
import {AssessmentClient,api} from '../../services/api';
import {ScreenCopilot} from './ScreenCopilot';
import {Field,Markdown,Modal} from './Primitives';
import {SCREEN_TEMPLATE} from '../../data/screen';
import {screenMemoProblems} from '../../screen-scoring';
const payload=(s:any)=>({scratchpad:s.scratchpad||'',finalDeliverable:s.finalDeliverable||'',...(s.branchingDecision?{branchingDecision:s.branchingDecision}:{})});
export function ScreenApp({initialSession,onSwitch}:{initialSession:any;onSwitch:()=>void}){
 const client=useMemo(()=>new AssessmentClient(initialSession),[initialSession.id]);
 const [s,setS]=useState(initialSession),[now,setNow]=useState(Date.now()),[error,setError]=useState(''),[status,setStatus]=useState('All changes saved'),[busy,setBusy]=useState(false),[tab,setTab]=useState('Briefing'),[drawer,setDrawer]=useState(false),[preview,setPreview]=useState(false),[editorMode,setEditorMode]=useState<'Editor'|'Split'|'Preview'>('Editor'),[alert,setAlert]=useState(initialSession.phase===3&&initialSession.status==='ACTIVE'&&initialSession.messages.some((m:any)=>m.isEmergency&&m.unread));
 const [rows,setRows]=useState<any[]>(()=>initialSession.track.dataGate.fields.map((f:any)=>initialSession.dataHygieneSelections?.find((r:any)=>r.fieldName===f.fieldName)||{fieldName:f.fieldName,action:'',rationale:''}));
 const [chat,setChat]=useState(initialSession.chatByPhase||{1:[],2:[],3:[],4:[],5:[]});
 const latest=useRef(s);latest.current=s;const pending=useRef(false),saved=useRef(JSON.stringify(payload(s)));
 const remaining=Math.max(0,Math.ceil((Date.parse(s.deadline)-now)/1000)),readonly=s.status!=='ACTIVE'||remaining===0,locked=!s.dataHandling||s.phase<2;
 const t=s.track,fingerprint=JSON.stringify(payload(s));
 const apply=(r:any)=>{const prior=latest.current;client.session=r;setS((current:any)=>({...r,...payload(current),...(r.phase>=3?{branchingDecision:r.branchingDecision}:{})}));if(r.phase===3&&prior.phase<3&&r.status==='ACTIVE')setAlert(true);};
 async function command(action='save',extra:object={}){
  if(pending.current)return null;pending.current=true;setBusy(true);setError('');
  const sent=payload(latest.current),mark=JSON.stringify(sent);
  try{const r=await client.command({action,...(!locked?{screen:sent}:{}),...extra});saved.current=mark;apply(r);setStatus('Saved');return r;}
  catch(e){setError((e as Error).message);setStatus('Save failed');try{const r=await api('/assessment?trackId='+encodeURIComponent(s.trackId));apply(r);}catch{}return null;}
  finally{pending.current=false;setBusy(false);}
 }
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const timer=setInterval(async()=>{if(pending.current)return;pending.current=true;try{const r=await api('/assessment?trackId='+encodeURIComponent(s.trackId));apply(r);}catch(e){setError((e as Error).message);}finally{pending.current=false;}},2000);return()=>clearInterval(timer);},[s.trackId]);
 useEffect(()=>{if(readonly||locked||saved.current===fingerprint||error)return;setStatus('Unsaved changes');const timer=setTimeout(()=>void command(),500);return()=>clearTimeout(timer);},[fingerprint,busy,locked,readonly,error]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(JSON.stringify(payload(latest.current))!==saved.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 const change=(patch:any)=>setS((old:any)=>({...old,...patch}));
 const branch=s.branchingDecision||{selectedOption:'',rationale:'',rejectedAlternatives:'',dependencies:'',owner:'',timing:'',triggerThreshold:''};

 const stage=s.phase===1?'Stage 1: Problem Framing':s.phase===2?'Stage 2: Baseline Analysis':'Stage 3: Operational Shock Adaptation';
 const memo=s.finalDeliverable||''; const words=memo.trim()?memo.trim().split(/\s+/).length:0; const chars=memo.length;
 return <div className="min-h-screen bg-zinc-950 text-zinc-100 flex flex-col"><header className="h-16 shrink-0 border-b border-zinc-800 bg-zinc-950 px-5 flex items-center gap-5"><div className="mr-auto flex items-center gap-3"><h1 className="text-sm font-semibold tracking-wide">AIMI Screen</h1><span className="text-[10px] uppercase tracking-[.18em] text-zinc-500">TRACK: {t.title.replace('AIMI Screen · ','')}</span><span className="rounded border border-zinc-700 px-2 py-1 text-[10px] text-zinc-300">{stage}</span></div><span role="timer" className="font-mono text-sm tabular-nums">{Math.floor(remaining/60).toString().padStart(2,'0')}:{String(remaining%60).padStart(2,'0')} REMAINING</span><span role="status" className="text-xs text-zinc-500">{busy?'Saving…':status}</span><button className="border border-zinc-700 px-3 py-1.5 text-xs rounded" disabled={busy||readonly||locked} onClick={()=>command()}>Save</button><button className="bg-zinc-100 text-zinc-950 px-3 py-1.5 text-xs rounded font-medium" disabled={locked} onClick={()=>setDrawer(true)}>Submit Session</button></header>
 {s.phase>=3&&<div className="shrink-0 bg-zinc-100 text-zinc-950 px-5 py-2 text-xs font-semibold tracking-wide">CRITICAL: Mid-Session Shock Active — Minute 20 Trigger Active — Impact: Operational Constraint Applied</div>}
 {error&&<div role="alert" className="work-warning m-3">{error} <button className="underline" onClick={()=>{setError('');void command();}}>Retry save</button></div>}
 {readonly&&<p className="p-3 bg-neutral-900 text-white">{s.status==='SUBMITTED'?'Submitted for human review.':'Time is up. Your last server-saved work is retained for grading.'}</p>}
 <div className="flex flex-1 min-h-0 overflow-hidden"><aside className="hidden lg:flex w-72 shrink-0 border-r border-zinc-800 bg-zinc-900/60 flex-col overflow-y-auto"><div className="p-4 border-b border-zinc-800"><p className="text-[10px] uppercase tracking-[.18em] text-zinc-500">Case exhibits & data</p><h2 className="mt-2 text-sm font-semibold">{t.companyName}</h2><p className="mt-2 text-xs text-zinc-400">{t.roleTitle}</p></div><nav className="p-2 grid gap-1">{['Briefing','Ex. 1','Ex. 2','Ex. 3','Shock'].map(v=><button key={v} disabled={locked||(v==='Shock'&&s.phase<3)} onClick={()=>setTab(v)} className={`text-left px-3 py-2 text-xs rounded ${tab===v?'bg-zinc-100 text-zinc-950':'text-zinc-400 hover:bg-zinc-800'}`}>{v}</button>)}</nav><div className="p-4 text-xs text-zinc-300"><p className="font-semibold tracking-wide">CORE ASSIGNMENT DELIVERABLE</p><p className="mt-2 text-zinc-500">Five-part executive memo with exactly one visual artifact.</p></div>{!locked&&<div className="p-4 border-t border-zinc-800"><p className="text-[10px] uppercase tracking-[.18em] text-zinc-500">Available exhibits</p>{t.exhibits.map((e:any)=><details key={e.id} className="mt-3 text-xs"><summary className="cursor-pointer text-zinc-300">{e.title}</summary><div className="mt-2 text-zinc-500"><Markdown text={e.content||''}/></div></details>)}</div>}</aside><main className="flex-1 min-w-0 overflow-auto bg-zinc-900"><div className="mx-auto max-w-4xl p-5 sm:p-8">
 <div className="flex items-center justify-between border-b border-zinc-800 pb-3 mb-5"><div className="flex gap-1"><button className={`px-3 py-1 text-xs rounded ${editorMode==='Editor'?'bg-zinc-100 text-zinc-950':'text-zinc-500'}`} onClick={()=>setEditorMode('Editor')}>Editor</button><button className={`px-3 py-1 text-xs rounded ${editorMode==='Split'?'bg-zinc-100 text-zinc-950':'text-zinc-500'}`} onClick={()=>setEditorMode('Split')}>Split</button><button className={`px-3 py-1 text-xs rounded ${editorMode==='Preview'?'bg-zinc-100 text-zinc-950':'text-zinc-500'}`} onClick={()=>setEditorMode('Preview')}>Preview</button></div><button className="text-xs text-zinc-400" onClick={()=>change({finalDeliverable:SCREEN_TEMPLATE})}>Reset structure</button></div>
 {!locked&&tab==='Briefing'&&<section className="mb-6"><p className="text-[10px] uppercase tracking-[.18em] text-zinc-500">CASE CONTEXT & ROLE BRIEF</p><h2 className="mt-2 text-2xl font-semibold">{t.companyName}</h2><p className="mt-4 text-sm leading-7 text-zinc-300">{t.companyBackground}</p><p className="mt-4 text-sm text-zinc-400">{t.activeObjective}</p></section>}
 {!locked&&tab==='Shock'&&s.phase>=3&&<section className="mb-6"><p className="text-[10px] uppercase tracking-[.18em] text-zinc-500">SHOCK UPDATE</p>{s.messages.filter((m:any)=>m.isEmergency).map((m:any)=><article key={m.id} className="mt-4 border border-zinc-700 bg-zinc-950 p-5"><h2 className="text-lg font-semibold">{m.subject}</h2><Markdown text={m.content.join('\n\n')}/></article>)}</section>}
 {!locked&&tab==='Scratchpad & decision'&&<fieldset disabled={readonly} className="space-y-6"><section><p className="text-[10px] uppercase tracking-[.18em] text-zinc-500">INTERACTIVE SCRATCHPAD</p><Field label="Analysis and working notes" value={s.scratchpad||''} rows={10} onChange={scratchpad=>change({scratchpad})}/></section><section><h2 className="text-lg font-semibold">Single Branching Decision</h2><p className="mt-2 text-sm text-zinc-400">Complete before minute 20. The original decision is preserved after the shock.</p><fieldset disabled={s.phase!==2} className="mt-4"><label className="work-field"><span>Selected path</span><select aria-label="Selected path" value={branch.selectedOption} onChange={e=>change({branchingDecision:{...branch,selectedOption:e.target.value}})}><option value="">Select a path</option>{t.branchingDecisions[0].options.map((o:any)=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>{[['rationale','Reasons for selected path'],['rejectedAlternatives','Reasons for rejecting alternatives'],['dependencies','Critical operational dependencies'],['owner','Primary owner'],['timing','Execution timeline'],['triggerThreshold','Quantitative reversal threshold']].map(([key,label])=><Field key={key} label={label} value={branch[key]} onChange={value=>change({branchingDecision:{...branch,[key]:value}})}/>)}</fieldset></section></fieldset>}
 {!locked&&tab==='Stakeholder inbox'&&s.messages.map((m:any)=><section className="mb-5 border border-zinc-800 bg-zinc-950 p-5" key={m.id}><h2 className="text-lg font-semibold">{m.subject}</h2><p className="mt-1 text-xs text-zinc-500">{m.senderRole} · {m.timestamp}</p><Markdown text={m.content.join('\n\n')}/>{m.unread&&!readonly&&<button className="mt-4 border border-zinc-700 px-3 py-1.5 text-xs" onClick={()=>command('open-message',{messageId:m.id})}>Mark read</button>}</section>)}
 {locked&&!readonly&&<section role="region" aria-label="Blocking data hygiene gate" className="border border-zinc-700 bg-zinc-950 p-5"><h2 className="text-lg font-semibold">Data Hygiene Gate</h2><p className="mt-2 text-sm text-zinc-400">{t.dataGate.description}</p>{s.dataHandling?<p className="mt-4 border border-zinc-700 p-3 text-sm">Gate passed. Analysis opens at 05:00; the clock is running.</p>:<form onSubmit={async e=>{e.preventDefault();const r=await command('data-handling',{dataHandling:rows});if(r&&!r.dataHandling)setError('Classification was not correct. Review every field and retry. This attempt is recorded.');}}><fieldset disabled={busy}>{rows.map((r,i)=><section key={r.fieldName} className="border-t border-zinc-800 py-4"><h3 className="text-sm font-medium">{r.fieldName}</h3><p className="mt-1 text-xs text-zinc-500">{t.dataGate.fields[i].description}</p><label className="work-field"><span>Handling for {r.fieldName}</span><select required value={r.action} onChange={e=>setRows(prev=>prev.map((v,j)=>j===i?{...v,action:e.target.value}:v))}><option value="">Choose handling</option>{['use-as-is','aggregate','redact','exclude'].map(v=><option key={v}>{v}</option>)}</select></label><Field label={`Rationale for ${r.fieldName}`} value={r.rationale} onChange={rationale=>setRows(prev=>prev.map((v,j)=>j===i?{...v,rationale}:v))}/></section>)}<button className="bg-zinc-100 text-zinc-950 px-4 py-2 text-xs rounded" disabled={rows.some(r=>!r.action||!r.rationale.trim())}>Submit field classifications</button></fieldset></form>}</section>}
 {tab==='Reference exhibits'&&<section className="space-y-5">{t.exhibits.map((e:any)=><article className="border border-zinc-800 bg-zinc-950 p-5" key={e.id}><h3 className="font-semibold">{e.title}</h3><Markdown text={e.content||''}/></article>)}</section>}
 <div className="mt-8 border-t border-zinc-800 pt-4 flex items-center justify-between text-xs text-zinc-500"><span>{words} words · {chars} chars · ~{Math.max(1,Math.ceil(words/200))} min read</span><button onClick={async()=>{if(saved.current===fingerprint||await command())onSwitch();}} className="text-zinc-400 hover:text-zinc-100">← Assessments</button></div></div></main>{!locked&&<ScreenCopilot session={s} chat={chat} disabled={readonly} onMessage={(phase,msg)=>setChat((old:any)=>({...old,[phase]:[...(old[phase]||[]),msg]}))}/>}</div>
 {drawer&&<Modal title="5-Part Executive Deliverable" onClose={()=>setDrawer(false)}><p className="work-muted">Exactly one Markdown table, matrix or fenced ASCII/Mermaid flowchart. Include two risks, monitoring thresholds, assumptions and justified confidence.</p><button className="work-secondary my-3" onClick={()=>setPreview(!preview)}>{preview?'Edit memo':'Preview memo'}</button>{!s.finalDeliverable&&!readonly&&<button className="work-secondary m-3" onClick={()=>change({finalDeliverable:SCREEN_TEMPLATE})}>Insert five section titles</button>}{preview?<Markdown text={s.finalDeliverable||''}/>:<fieldset disabled={readonly}><Field label="Executive memo Markdown" value={s.finalDeliverable||''} rows={22} onChange={finalDeliverable=>change({finalDeliverable})}/></fieldset>}<p className="text-sm my-3">{screenMemoProblems(s.finalDeliverable||'').join(' ')||'Five sections and one visual detected. Review content before submitting.'}</p><button className="work-primary" disabled={busy||readonly||s.phase!==3} onClick={async()=>{if(await command('advance'))setDrawer(false);}}>Submit final memo</button></Modal>}
 {alert&&!locked&&!readonly&&<Modal title="URGENT: New Mid-Scenario Constraint — Immediate Attention Required" onClose={()=>setAlert(false)}><p>A material development may invalidate part of your current recommendation. Open the Stakeholder Inbox to review revised facts and required deliverable changes.</p><button className="work-primary mt-5" onClick={()=>{setAlert(false);setTab('Stakeholder inbox');}}>Open Stakeholder Inbox</button></Modal>}
 </div>;
}
