import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {queryCopilot} from '../../services/aiCopilot';
import {api} from '../../services/api';
import {Markdown} from './Primitives';
export function ScreenCopilot({session,chat,onMessage,disabled}:{session:any;chat:any;onMessage:(phase:number,message:any)=>void;disabled:boolean}){
 const [open,setOpen]=useState(()=>window.innerWidth>=1280),[prompt,setPrompt]=useState(''),[purpose,setPurpose]=useState(''),[busy,setBusy]=useState(false),[stream,setStream]=useState(''),[error,setError]=useState(''),[model,setModel]=useState('Groq Cloud');
 const scroll=useRef<HTMLDivElement>(null),following=useRef(true);
 const messages=Object.values(chat).flat() as any[];
 useEffect(()=>{const resize=()=>{if(window.innerWidth<1280)setOpen(false);};window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
 useEffect(()=>{api('/copilot/config').then(c=>setModel(c.model)).catch(()=>{});},[]);
 useLayoutEffect(()=>{const el=scroll.current;if(el&&following.current&&!el.querySelector('.work-table-wrap:hover, .work-table-wrap:focus-within'))el.scrollTop=el.scrollHeight;},[stream,messages.length,open]);
 async function send(e:React.FormEvent){e.preventDefault();if(disabled||busy||!prompt.trim()||!purpose.trim())return;const phase=session.phase,text=prompt.trim();setBusy(true);setError('');setPrompt('');onMessage(phase,{id:crypto.randomUUID(),sender:'user',content:text,timestamp:new Date().toISOString()});
  try{const r=await queryCopilot({sessionId:session.id,trackId:session.track.id,phaseId:phase,modelId:model,prompt:text,loggedPurpose:purpose,privateDataShared:false,aiVerificationEnabled:false},setStream,setModel);onMessage(phase,{id:r.logId+'-response',sender:'assistant',content:r.reply,timestamp:new Date().toISOString()});}catch(e){setError((e as Error).message);}finally{setBusy(false);setStream('');}
 }
 if(!open)return <button className="fixed bottom-5 right-5 work-primary z-30" onClick={()=>setOpen(true)}>AI Copilot</button>;
 return <aside aria-label="Screen Copilot" className="fixed inset-y-0 right-0 z-40 w-full sm:w-[420px] xl:static xl:shrink-0 bg-white border-l flex flex-col min-h-0 shadow-xl"><header className="p-4 border-b flex gap-3 items-center"><div className="mr-auto"><h2>AI Copilot</h2><p className="text-xs text-neutral-500">{model}</p></div><button className="work-secondary" onClick={()=>setOpen(false)}>Close Copilot</button></header><div className="flex-1 overflow-y-auto min-w-0 p-4 space-y-5" ref={scroll} onScroll={()=>{const el=scroll.current;if(el)following.current=el.scrollTop+el.clientHeight>=el.scrollHeight-60;}}>{messages.filter(m=>m.sender==='user'||m.sender==='assistant').map(m=><article key={m.id} className="min-w-0"><strong className="text-xs uppercase text-neutral-500">{m.sender==='user'?'You':'Copilot'}</strong><div className="w-full overflow-x-auto my-2"><Markdown text={m.content}/></div></article>)}{stream&&<article className="min-w-0"><strong>Copilot</strong><div className="w-full overflow-x-auto my-2"><Markdown text={stream}/></div></article>}{busy&&!stream&&<p role="status">Copilot is thinking…</p>}</div>{error&&<p role="alert" className="work-warning m-3">{error}</p>}<form onSubmit={send} className="p-4 border-t"><fieldset disabled={disabled||busy}><label className="work-field"><span>Query purpose</span><input value={purpose} onChange={e=>setPurpose(e.target.value)} placeholder="Verify arithmetic or compare options" required maxLength={2000}/></label><label className="work-field"><span>Ask Copilot</span><textarea rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} required maxLength={16000} placeholder="Use sanitized case data only"/></label><button className="work-primary" disabled={!prompt.trim()||!purpose.trim()}>Send query</button></fieldset><p className="work-muted text-xs mt-3">Queries and responses are logged for review. Verify and edit generated work.</p></form></aside>;
}
