import React,{useEffect,useState} from 'react';
import type {AssessmentWork,Visual,WorkDocument} from '../../types/work';
import {Field,Modal} from './Primitives';
import {api, authHeaders} from '../../services/api';
export function Chart({visual:v}:{visual:Visual}) {const max=Math.max(...v.rows.map(r=>Math.abs(r.value)),1);return <figure className="work-card"><h3>{v.title||'Untitled visual'}</h3><p className="work-muted text-xs">{v.unit}</p>{v.kind==='bar'?v.rows.map((r,i)=><div key={i} className="my-3"><div className="flex justify-between text-xs gap-4"><span>{r.label}</span><strong>{r.value.toLocaleString()}</strong></div><div className="h-3 bg-neutral-100 mt-1 rounded"><div className={`h-3 rounded ${r.value<0?'bg-neutral-400':'bg-neutral-800'}`} style={{width:Math.abs(r.value)/max*100+'%'}}/></div></div>):<div className="work-table-wrap"><table><tbody>{v.rows.map((r,i)=><tr key={i}><td>{r.label}</td><td>{r.value.toLocaleString()}</td></tr>)}</tbody></table></div>}<figcaption className="mt-4 text-sm"><strong>Takeaway:</strong> {v.takeaway||'Add a decision-oriented takeaway.'}<p className="work-muted text-xs mt-2">Source: {v.source||'Not cited'}</p></figcaption></figure>;}
export function DocumentView({doc,work}:{doc:WorkDocument;work:AssessmentWork}) {return <div className="work-stack">{doc.pages.map((p,i)=><article className="work-card" key={i}><p className="work-eyebrow">{doc.kind==='deck'?'Slide':'Page'} {i+1} · {doc.stage}</p><h2>{p.headline}</h2><p className="whitespace-pre-wrap leading-relaxed mb-4">{p.body}</p>{p.visualIds.map(id=>{const visual=work.visuals.find(v=>v.id===id);return visual?<Chart key={id} visual={visual}/>:null;})}</article>)}</div>;}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function exportDocument(doc:WorkDocument,w:AssessmentWork){
 const popup=window.open('','_blank');if(!popup)return;popup.opener=null;
 const pages=doc.pages.map((p,i)=>`<article><small>${doc.kind==='deck'?'SLIDE':'PAGE'} ${i+1} · ${escape(doc.stage)}</small><h1>${escape(p.headline)}</h1><p>${escape(p.body)}</p>${p.visualIds.map(id=>{const v=w.visuals.find(v=>v.id===id);if(!v)return '';const max=Math.max(...v.rows.map(r=>Math.abs(r.value)),1);return `<section><h2>${escape(v.title)}</h2><small>${escape(v.unit)}</small>${v.rows.map(r=>`<div>${escape(r.label)} <b>${r.value.toLocaleString()}</b>${v.kind==='bar'?`<div style="height:8px;background:#222;width:${Math.abs(r.value)/max*100}%"></div>`:''}</div>`).join('')}<p><b>Takeaway:</b> ${escape(v.takeaway)}</p><small>Source: ${escape(v.source)}</small></section>`;}).join('')}</article>`).join('');
 popup.document.write(`<html><head><title>${escape(doc.title)}</title><style>@page{size:${doc.kind==='deck'?'A4 landscape':'A4'};margin:14mm}body{font:14px -apple-system,Arial,sans-serif;color:#222}article{break-after:page;max-width:100%;padding:18px}article:last-child{break-after:auto}h1{font-size:28px}p{white-space:pre-wrap;line-height:1.55}small{color:#666}section{border:1px solid #ddd;padding:16px;margin:16px 0}section div{margin:8px 0}button{padding:10px}@media print{button{display:none}}</style></head><body><button id="print">Print / Save as PDF</button>${pages}</body></html>`);popup.document.close();popup.document.getElementById('print')!.onclick=()=>popup.print();
}
export function Attachments({sessionId,readOnly=false}:{sessionId:string;readOnly?:boolean}){const [files,setFiles]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=()=>api(`/assessment/${sessionId}/artifacts`).then(setFiles).catch(e=>setError(e.message));useEffect(()=>{void load();},[sessionId]);async function upload(file:File){setError('');setBusy(true);try{const response=await fetch(`/api/assessment/${sessionId}/artifacts`,{method:'POST',credentials:'same-origin',headers:{...(await authHeaders('application/octet-stream')),'X-File-Name':encodeURIComponent(file.name)},body:file});const result=await response.json();if(!response.ok)throw new Error(result.error);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <section className="work-card"><h3>Supporting files</h3><p className="work-muted">Files are retained for human review. Native drafts and final fields remain required. Maximum 5 MB per file.</p>{!readOnly&&<label className="work-field"><span>{busy?'Uploading…':'Upload an artifact'}</span><input type="file" disabled={busy} accept=".pdf,.png,.jpg,.jpeg,.pptx,.xlsx,.csv,.txt" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>}{error&&<p role="alert">{error}</p>}{files.map(f=><p key={f.id} className="my-2"><a className="underline" href={`/api/assessment/${sessionId}/artifacts/${f.id}`}>{f.name}</a> <small>· Segment {f.phase} · {(f.size/1024).toFixed(1)} KB</small></p>)}</section>;}
export function Studio({work,onChange,phase,sessionId}:{work:AssessmentWork;onChange:(w:AssessmentWork)=>void;phase:number;sessionId:string}){
 const [tab,setTab]=useState('Visuals'),[preview,setPreview]=useState<string|null>(null);
 const updateVisual=(id:string,patch:Partial<Visual>)=>onChange({...work,visuals:work.visuals.map(v=>v.id===id?{...v,...patch}:v)});
 const updateDoc=(id:string,patch:Partial<WorkDocument>)=>onChange({...work,documents:work.documents.map(d=>d.id===id?{...d,...patch}:d)});
 function addDoc(kind:WorkDocument['kind']){onChange({...work,documents:[...work.documents,{id:crypto.randomUUID(),phase,kind,stage:'draft',title:'',pages:[{headline:'',body:'',visualIds:[]}]}]});}
 return <div className="work-stack"><nav className="work-tabs">{['Visuals','Decks & memos','Files'].map(t=><button key={t} onClick={()=>setTab(t)} aria-pressed={tab===t}>{t}</button>)}</nav>
 {tab==='Visuals'&&<><p className="work-muted">Build a chart or comparison table. Include the unit, source and the decision it supports.</p>{work.visuals.map(v=><section className="work-card" key={v.id}><p className="work-eyebrow">Segment {v.phase}</p><Field label="Visual title" value={v.title} onChange={title=>updateVisual(v.id,{title})} rows={1}/><div className="work-grid-2"><label className="work-field"><span>Visual type</span><select aria-label="Visual type" value={v.kind} onChange={e=>updateVisual(v.id,{kind:e.target.value as Visual['kind']})}><option value="bar">Bar chart</option><option value="table">Comparison table</option></select></label><Field label="Unit / denominator" value={v.unit} onChange={unit=>updateVisual(v.id,{unit})} rows={1}/></div>{v.rows.map((r,i)=><div className="flex gap-2 items-end" key={i}><label className="work-field flex-1"><span>Label {i+1}</span><input value={r.label} onChange={e=>updateVisual(v.id,{rows:v.rows.map((x,j)=>i===j?{...x,label:e.target.value}:x)})}/></label><label className="work-field w-28"><span>Value {i+1}</span><input type="number" step="any" value={r.value} onChange={e=>updateVisual(v.id,{rows:v.rows.map((x,j)=>i===j?{...x,value:Number(e.target.value)}:x)})}/></label><button className="mb-5" aria-label={`Remove row ${i+1}`} onClick={()=>updateVisual(v.id,{rows:v.rows.filter((_,j)=>j!==i)})}>✕</button></div>)}<button className="work-secondary" onClick={()=>updateVisual(v.id,{rows:[...v.rows,{label:'',value:0}]})}>Add data row</button><Field label="Visual source" value={v.source} onChange={source=>updateVisual(v.id,{source})}/><Field label="Executive takeaway" value={v.takeaway} onChange={takeaway=>updateVisual(v.id,{takeaway})}/><Chart visual={v}/></section>)}<button className="work-primary" onClick={()=>onChange({...work,visuals:[...work.visuals,{id:crypto.randomUUID(),phase,title:'',kind:'bar',unit:'',takeaway:'',source:'',rows:[{label:'',value:0},{label:'',value:0}]}]})}>Create visual</button></>}
 {tab==='Decks & memos'&&<><p className="work-muted">Use assertion headlines that state the answer. Build drafts here, then create or copy a separate final version after the update.</p><div className="flex gap-2 flex-wrap">{(['deck','memo','dashboard'] as const).map(k=><button key={k} className="work-secondary" onClick={()=>addDoc(k)}>New {k}</button>)}</div>{work.documents.map(d=><section className="work-card" key={d.id}><p className="work-eyebrow">{d.kind} · Created in segment {d.phase} · {d.pages.length} pages</p><Field label="Document title" value={d.title} onChange={title=>updateDoc(d.id,{title})} rows={1}/><label className="work-field"><span>Document status</span><select aria-label="Document status" value={d.stage} onChange={e=>updateDoc(d.id,{stage:e.target.value as any})}><option value="draft">Draft</option><option value="final">Final</option></select></label>{d.pages.map((p,i)=><div key={i} className="border-t border-neutral-200 pt-3 mt-4"><h3>{d.kind==='deck'?'Slide':'Page'} {i+1}</h3><Field label={`Assertion headline ${i+1}`} value={p.headline} onChange={headline=>updateDoc(d.id,{pages:d.pages.map((x,j)=>i===j?{...x,headline}:x)})} rows={1}/><Field label={`Page ${i+1} narrative / evidence / actions`} value={p.body} onChange={body=>updateDoc(d.id,{pages:d.pages.map((x,j)=>i===j?{...x,body}:x)})} rows={5}/><p className="text-xs mb-2">Include visuals:</p>{work.visuals.map(v=><label key={v.id} className="flex gap-2 my-2 text-sm"><input type="checkbox" checked={p.visualIds.includes(v.id)} onChange={e=>updateDoc(d.id,{pages:d.pages.map((x,j)=>i===j?{...x,visualIds:e.target.checked?[...x.visualIds,v.id]:x.visualIds.filter(id=>id!==v.id)}:x)})}/>{v.title||'Untitled visual'}</label>)}{d.pages.length>1&&<button className="text-xs underline" onClick={()=>updateDoc(d.id,{pages:d.pages.filter((_,j)=>i!==j)})}>Remove page</button>}</div>)}<div className="flex gap-2 flex-wrap mt-5"><button disabled={d.pages.length>=5} className="work-secondary" onClick={()=>updateDoc(d.id,{pages:[...d.pages,{headline:'',body:'',visualIds:[]}]})}>Add page</button><button className="work-secondary" onClick={()=>setPreview(d.id)}>Preview</button><button className="work-secondary" onClick={()=>exportDocument(d,work)}>Export / Print PDF</button><button className="work-secondary" onClick={()=>onChange({...work,documents:[...work.documents,{...structuredClone(d),id:crypto.randomUUID(),phase,stage:'final',title:d.title+' — final'}]})}>Copy as final</button></div></section>)}</>}
 {tab==='Files'&&<Attachments sessionId={sessionId}/>}
 {preview&&<Modal title="Document preview" onClose={()=>setPreview(null)}><DocumentView doc={work.documents.find(d=>d.id===preview)!} work={work}/></Modal>}
 </div>;
}
