import React,{useState} from 'react';
import {api} from '../../services/api';
import {Markdown,Field} from '../revised/Primitives';
import {effectiveScreenCaps,scoreScreen,EMPTY_SCREEN_CAPS, type ScreenCaps} from '../../screen-scoring';
import {PromptAuditPlayer} from './PromptAuditPlayer';
export function AIMIScreenGrader({record,canScore}:{record:any;canScore:boolean}){
 const [evaluation,setEvaluation]=useState(record.evaluation),[scores,setScores]=useState<Record<string,{score:number;notes:string}>>(record.evaluation?.scores||{}),[flags,setFlags]=useState<ScreenCaps>({...EMPTY_SCREEN_CAPS,...record.evaluation?.screenCaps}),[feedback,setFeedback]=useState(record.evaluation?.feedback||''),[decision,setDecision]=useState(record.evaluation?.humanDecision||''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const caps=effectiveScreenCaps(record,flags),result=scoreScreen(scores,caps,record.scenarioSnapshot.id),readonly=!canScore||busy||!!evaluation?.finalizedAt||record.status==='ACTIVE';
 async function save(finalize:boolean){setBusy(true);try{const r=await api(`/grader/${record.id}/evaluation`,{revision:evaluation.revision,scores,screenCaps:flags,feedback,humanDecision:decision,planningCapApplied:false,finalize});setEvaluation({...evaluation,revision:r.revision,overallScore:r.overallScore,finalizedAt:finalize?new Date().toISOString():null});setMessage(`Saved: ${r.overallScore}/100`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const labels:[keyof ScreenCaps,string][]=[['privacyLeak','Actual unmasked identifier disclosure · overall cap 60'],['gateFailure','Gate failure or bypass · overall cap 60'],['shockNonAdaptation','No substantive shock adaptation · adaptability 4/10; recommendation 10/15'],['missingVisual','Missing visual · synthesis 10/18'],...(record.scenarioSnapshot.id==='product-management'?[['pmBroadLaunch','Retained broad full launch post-shock · overall cap 50'] as [keyof ScreenCaps,string]]:[]),...(record.scenarioSnapshot.id==='consulting'?[['consultingUnsafeExpansion','Expanded Sales without routing remediation · adaptability 4/10'] as [keyof ScreenCaps,string]]:[]),...(record.scenarioSnapshot.id==='investment-banking'?[['ibMissingDownside','Settlement / distributor loss omitted from price mechanics · recommendation 7/15'] as [keyof ScreenCaps,string]]:[])];
 return <div className="flex-1 overflow-auto p-4 grid gap-4 lg:grid-cols-2"><main className="work-stack min-w-0"><section className="work-card"><p className="work-eyebrow">{record.status} · AIMI Screen</p><h2>{record.scenarioSnapshot.title}</h2><h3 className="mt-4">Final executive memo</h3><Markdown text={record.finalDeliverable||'No memo saved.'}/></section><section className="work-card"><h3>Pre-shock memo checkpoint</h3><Markdown text={record.checkpoints.find((c:any)=>c.phase===2)?.snapshot.finalDeliverable||'No pre-shock memo saved.'}/><h3 className="mt-4">Single branching decision</h3>{Object.entries(record.branchingDecision||{}).map(([k,v])=><p className="my-3 whitespace-pre-wrap" key={k}><strong>{k}: </strong>{String(v)}</p>)}<h3>Scratchpad</h3><Markdown text={record.scratchpad||'No notes saved.'}/></section><section className="work-card"><h3>Data hygiene evidence</h3>{record.hygieneEvents.map((e:any,i:number)=><details className="py-3 border-t" key={i}><summary>{e.type} · {e.at}{e.passed===undefined?'':e.passed?' · Passed':' · Failed attempt'}</summary>{e.decisions?.map((d:any)=><p key={d.fieldName}>{d.fieldName}: {d.action} — {d.rationale}</p>)}<p>{e.fields?.join(', ')}</p></details>)}<p className="work-muted">Blocked identifier attempts did not reach the provider. Review recorded evidence before marking actual disclosure.</p></section><section className="work-card"><h3>Quantitative reference</h3><p>{record.evidence?.baselineNotes}</p></section><section className="work-card min-h-[500px]"><h3>Copilot audit</h3><PromptAuditPlayer sessionId={record.id}/></section></main>
 <aside className="work-stack min-w-0"><section className="work-card"><h2>{evaluation?.finalizedAt?evaluation.overallScore:result.total} / 100</h2><p>AI Interaction & Decision-Making: {result.interaction}/45</p><p>Final Executive Deliverable: {result.deliverable}/55</p><p className="work-muted">Uncapped total: {result.uncapped}. Applied ceiling: {result.ceiling}.</p></section><fieldset disabled={readonly} className="work-stack"><section className="work-card"><h3>Hard caps · evidence required</h3>{labels.map(([key,label])=><label className="flex gap-3 my-4" key={key}><input type="checkbox" checked={!!caps[key]} disabled={!!caps[key]&&!flags[key]} onChange={e=>setFlags({...flags,[key]:e.target.checked})}/>{label}</label>)}<Field label="Cap findings and evidence references" value={flags.evidence} onChange={evidence=>setFlags({...flags,evidence})}/><h3>Grader calibration</h3><p className="work-muted">Would you trust independent operation within two weeks? Did the candidate prioritize and adapt under pressure? Did they maintain hygiene and use AI analytically?</p><label className="work-field"><span>Number of “No” answers</span><select value={flags.calibrationNo} onChange={e=>setFlags({...flags,calibrationNo:Number(e.target.value)})}>{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label>{flags.calibrationNo>=2&&<p className="work-warning">Overall cap 74. Re-audit every pillar above 80% against evidence.</p>}</section>
 {record.rubricSnapshot.map((c:any)=><section className="work-card" key={c.id}><h3>{c.name} · {c.maxScore} points</h3><details className="my-3"><summary>Calibration anchors</summary><p>{c.anchorStrong}</p><p>{c.anchorMid}</p><p>{c.anchorWeak}</p></details><label className="work-field"><span>{c.name} score</span><input type="number" min={0} max={c.maxScore} value={scores[c.id]?.score??''} onChange={e=>setScores({...scores,[c.id]:{score:Number(e.target.value),notes:scores[c.id]?.notes||''}})}/></label><p className="work-muted">After caps: {result.points[c.id]}/{c.maxScore}</p><Field label={`${c.name} evidence`} value={scores[c.id]?.notes||''} onChange={notes=>setScores({...scores,[c.id]:{score:scores[c.id]?.score||0,notes}})}/></section>)}<section className="work-card"><Field label="Qualitative feedback" value={feedback} onChange={setFeedback}/><Field label="Human evaluation decision" value={decision} onChange={setDecision}/><div className="flex gap-3"><button className="work-secondary" onClick={()=>save(false)}>Save evaluation</button><button className="work-primary" onClick={()=>save(true)}>Finalize human evaluation</button></div></section></fieldset>{message&&<p role="status" className="work-warning">{message}</p>}</aside></div>;
}
